# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: arima-env
dependencies:
- python=3.6.9

- pip:
  - azureml-sdk
  - azureml-dataset-runtime
  - statsmodels==0.12.2
  - scikit-learn
  - joblib
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - numpy
channels:
- anaconda
- conda-forge
