name: arima-env
dependencies:
- python=3.6.9

- pip:
  - azureml-sdk
  - azureml-dataset-runtime
  - statsmodels==0.12.2
  - scikit-learn
  - joblib
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - numpy
channels:
- anaconda
- conda-forge
